version: '3'

services:
  server:
    build:
      context: .
    ports:
      - "5100:5100"
  client:
    image: andylippitt/daud-client:d12
    build:
      context: ./Client/
      

    ports:
      - "80:80" 