apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-robots-duel
  labels:
    app: game-robots-duel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-robots-duel
  template:
    metadata:
      name: game-robots-duel
      labels:
        app: game-robots-duel
    spec:
      containers:
        - name: game-robots-duel
          image: iodaud/daud:version-1.32
          resources:
          command: ["dotnet"]
          args: ["/app/Game.Util/bin/Release/netcoreapp3.1/publish/Game.Util.dll",
            "--server", "https://us.daud.io/", 
            "--user-key", "Administrator", 
            "--password", "DaudsEverywhere", 
            "player", "robots",
            "--scenario", "https://raw.githubusercontent.com/daud-io/daud/master/Samples/Robots/Scenarios/AvsB.json"
            ]
          volumeMounts:
            - name: nfsvol
              mountPath: /mnt/q
              subPath: home/game
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: nfs-pvc
---