// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from "flatbuffers";

export class NetAuthenticate {
    bb: flatbuffers.ByteBuffer | null = null;
    bb_pos = 0;
    __init(i: number, bb: flatbuffers.ByteBuffer): NetAuthenticate {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }

    static getRootAsNetAuthenticate(bb: flatbuffers.ByteBuffer, obj?: NetAuthenticate): NetAuthenticate {
        return (obj || new NetAuthenticate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }

    static getSizePrefixedRootAsNetAuthenticate(bb: flatbuffers.ByteBuffer, obj?: NetAuthenticate): NetAuthenticate {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new NetAuthenticate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }

    token(): string | null;
    token(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    token(optionalEncoding?: any): string | Uint8Array | null {
        const offset = this.bb!.__offset(this.bb_pos, 4);
        return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
    }

    static startNetAuthenticate(builder: flatbuffers.Builder) {
        builder.startObject(1);
    }

    static addToken(builder: flatbuffers.Builder, tokenOffset: flatbuffers.Offset) {
        builder.addFieldOffset(0, tokenOffset, 0);
    }

    static endNetAuthenticate(builder: flatbuffers.Builder): flatbuffers.Offset {
        const offset = builder.endObject();
        return offset;
    }

    static createNetAuthenticate(builder: flatbuffers.Builder, tokenOffset: flatbuffers.Offset): flatbuffers.Offset {
        NetAuthenticate.startNetAuthenticate(builder);
        NetAuthenticate.addToken(builder, tokenOffset);
        return NetAuthenticate.endNetAuthenticate(builder);
    }
}
