// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Game.Engine.Networking.FlatBuffers
{

public enum AllMessages : byte
{
 NONE = 0,
 NetWorldView = 1,
 NetHello = 2,
 NetSpawn = 3,
 NetControlInput = 4,
 NetPing = 5,
 NetLeaderboard = 6,
};


}
