// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Game.Engine.Networking.FlatBuffers
{

public enum AllMessages : byte
{
 NONE = 0,
 WorldView = 1,
 Hello = 2,
 Spawn = 3,
 ControlInput = 4,
 Ping = 5,
};


}
