namespace Game.Engine.Core
{
    public enum Sprites : byte
    {
        None,
        ship0,
        ship_green,
        ship_gray,
        ship_orange,
        ship_pink,
        ship_red,
        ship_cyan,
        ship_yellow,
        ship_flash,
        bullet_green,
        bullet_orange,
        bullet_pink,
        bullet_red,
        bullet_cyan,
        bullet_yellow,
        fish,
        bullet,
        seeker,
        seeker_pickup,
        obstacle,
        arrow,
        flag_blue_0,
        flag_blue_1,
        flag_blue_2,
        flag_blue_3,
        flag_blue_4,
        flag_red_0,
        flag_red_1,
        flag_red_2,
        flag_red_3,
        flag_red_4
    }
}
